### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by OlliV** [nikkan/tiralabra#1]
Koodi on erittäin selkeästi kirjoitettua ja helppoa lukea, joskin paikoin itse erottelisin hieman enemmän koodia tyhjillä riveillä väleissä. Erityisesti metodin/lohokon alussa muuttujien esittelyn ja muun alkavan koodin välissä on yleensä tottunut näkemään tyhjän rivin.

Kommentointi on hyvinkin riittävää vaikka koodin seassa ei hirveästi kommentteja olekaan, koska metodit ovat pääosin hyvin lyhyitä. Moni on jopa sitä mieltä, että metodien sisällä ei pitäisi juuri kommentteja edes olla vaan metodin nimen ja kuvauksen pitäisi riittää siihen, että ymmärtää mitä metodi tekee.

Pystyisin helposti jatkamaan toteutusta ilman muuta dokumentaatiota toteutuksesta, koska koodista ja kommenteista ymmärtää suhteellisen helposti mitä minkäkin metodin ja osan on tarkoitus tehdä.

Koodia voisi hieman parantaa poistamalla koodin toistoa mitä esiintyy ainakin muutamassa metodissa ja luokassa (esim. keon swapit). Lisäksi uloskommentoitua koodia kannattaa harkita poistettavaksi, koska rivit säilyvät kuitenkin git:ssä. On tavallaan turhaa laittaa git:n kahta kopioita samoista riveistä missä toisessa kopiossa rivien alkuun on lisätty '//'.

Koodin ulos kommentointiin liittyen monesti isommissa projekteissa näkee, että ulos kommentoidulla koodilla halutaan näyttää, että jonkin asian tekeminen ei ole välttämätöntä jostakin syystä vaikka olisikin esim. algoritmin kannalta oikeampi tapa.
Toinen tapaus on varmaankin näyttää vanha tapa tehdä jokin asia uuden rinnalla.

Näin vähäisellä omalla Java-osaamisella sanoisin kuitenkin, että erittäin nättiä koodia ja on aika vaikea keksiä mitään erityisen huonoa totetustavasta.

**Comment by nikkan** [comment]
Kiitos hyvistä kommenteista, otan varmasti huomioon refaktoroidessa koodia! :)
